CREATE TABLE IF NOT EXISTS llx_fin_dossiers_rachetes
(
    rowid                            int(11) NOT NULL primary key AUTO_INCREMENT,
    fk_dossier                       int(11) NOT NULL,
    retrait_copie_sup                int     NOT NULL DEFAULT 0,
    decompte_copies_sup              int     NOT NULL DEFAULT 0,
    date_debut_periode_leaser        date             default null,
    date_fin_periode_leaser          date             default null,
    solde_banque_a_periode_identique float   not null default 0,
    type_contrat                     varchar(255)     default null, -- Champ tout le temps à NULL dans mes tests
    duree                            varchar(10)      default null,
    echeance                         int     not null default 0,
    loyer_actualise                  float   not null default 0,
    date_debut                       date             default null,
    date_fin                         date             default null,
    date_prochaine_echeance          date             default null,
    numero_prochaine_echeance        int     not null default 0,
    terme                            varchar(10)      default null,
    reloc                            varchar(5)       default null,
    maintenance                      float   not null default 0,
    assurance                        float   not null default 0,
    assurance_actualise              float   not null default 0,
    montant                          float   not null default 0,
    date_debut_periode_client_m1     date             default null,
    date_fin_periode_client_m1       date             default null,
    solde_vendeur_m1                 float   not null default 0,
    solde_banque_m1                  float   not null default 0,
    date_debut_periode_client        date             default null,
    date_fin_periode_client          date             default null,
    solde_vendeur                    float   not null default 0,
    solde_banque                     float   not null default 0,
    date_debut_periode_client_p1     date             default null,
    date_fin_periode_client_p1       date             default null,
    solde_vendeur_p1                 float   not null default 0,
    solde_banque_p1                  float   not null default 0,
    choice                           varchar(5)       default null,
    foreign key (fk_dossier) references llx_fin_dossier (rowid)
) ENGINE = MyISAM
  DEFAULT CHARSET = utf8;
